# .cpanel.yml
---
deploy:
  commands:
    # Navigate to the application directory
    - cd /home/aicdf

    # Install dependencies
    - npm install

    # Build the Next.js application
    - npm run build

    # Install PM2 globally if not already installed
    - npm install -g pm2

    # Stop existing PM2 process (ignore errors if not running)
    - pm2 stop aicdf || true

    # Start the application with PM2
    - pm2 start npm --name "aicdf" -- run start

    # Save PM2 process list and corresponding environments
    - pm2 save
