# .cpanel.yml
---
deploy:
  commands:
    # Navigate to the application directory
    - cd /home/aiai11255/repositories/companyportfolio || { echo 'Directory not found'; exit 1; }

    # Install dependencies
    - npm install || { echo 'npm install failed'; exit 1; }

    # Build the Next.js application
    - npm run build || { echo 'Build failed'; exit 1; }

    # Stop existing PM2 process (ignore errors if not running)
    - pm2 stop ACIDF || true

    # Start the application with PM2
    - pm2 start npm --name "ACIDF" -- run start || { echo 'Failed to start app'; exit 1; }

    # Save PM2 process list and corresponding environments
    - pm2 save || { echo 'Failed to save pm2 process'; exit 1; }
